### ISSUE TITLE
[0.2.0] CristelLib funny moments :(

### ISSUE THREAD

**Issue by aninusmuffin** [tazta2ra/bluelotus-beyond-old#4]
Until this issue is fixed **Towns and Towers** cant be used in the pack

This is agony

This happens with CristelLib 1.1.1 quilt

```
---- Crashed! ----
Date/Time: 2023/08/01 16:11:19.4458

-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'blue.endless.jankson.JsonPrimitive blue.endless.jankson.JsonPrimitive.of(java.lang.Boolean)'
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:526)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoSuchMethodError: 'blue.endless.jankson.JsonPrimitive blue.endless.jankson.JsonPrimitive.of(java.lang.Boolean)'
	at net.cristellib.config.ConfigUtil.createConfig(ConfigUtil.java:49)
	at net.cristellib.StructureConfig.writeConfig(StructureConfig.java:103)
	at net.cristellib.CristelLib.preInit(CristelLib.java:33)
	at net.minecraft.class_2966.handler$jio000$cristellib$loadPacks(class_2966.java:2014)
	at net.minecraft.class_2966.method_12851(class_2966.java:76)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	... 5 more

```

**Comment by aninusmuffin** [comment]
I found a workaround i think this can be closed
